#if UNITY_EDITOR
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections.Generic;
using UnityEditor;
using UnityEngine;

namespace TrashCount.Data.Generators
{
    public static class EnumGenerator
    {
        public static void GenerateFromDictionary<V>(string fileName, Dictionary<string, V> dict)
        {
            if (dict == null || dict.Count == 0) return;

            StringBuilder sb = new();
            sb.AppendLine("// ========================================================");
            sb.AppendLine("// AUTO-GENERATED BY TRASHCOUNT EDITOR. DO NOT EDIT!");
            sb.AppendLine("// ========================================================");
            sb.AppendLine("namespace TrashCount.Data");
            sb.AppendLine("{");
            sb.AppendLine($"    public enum {fileName}");
            sb.AppendLine("    {");
            sb.AppendLine("        None = 0,");

            HashSet<string> usedKeys = new();

            foreach (var key in dict.Keys)
            {
                if (string.IsNullOrWhiteSpace(key)) continue;

                string cleanKey = Regex.Replace(key.Trim(), @"[^\w]", "_");
                if (char.IsDigit(cleanKey[0]))
                {
                    cleanKey = "_" + cleanKey;
                }

                if (usedKeys.Add(cleanKey))
                {
                    sb.AppendLine($"        {cleanKey},");
                }
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            string dirPath = Path.Combine(Application.dataPath, "Scripts", "Generated");
            if (!Directory.Exists(dirPath))
            {
                Directory.CreateDirectory(dirPath);
            }

            string filePath = Path.Combine(dirPath, fileName + ".cs");
            string newContent = sb.ToString();

            if (File.Exists(filePath) && File.ReadAllText(filePath) == newContent) return;

            File.WriteAllText(filePath, newContent);
            AssetDatabase.Refresh();
        }
    }
}
#endif