#if UNITY_EDITOR
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;

namespace TrashCount.Data.Generators
{
    public static class EnumGenerator
    {
        /// <summary>
        /// Generates a strongly-typed Enum, Partial Class Indexer, and Lookup Extension for ANY dictionary type!
        /// </summary>
        /// <typeparam name="TValue">The model or value type stored in the dictionary (e.g. float, ItemBaseModel, etc.)</typeparam>
        /// <param name="enumName">Name of the Enum to generate (e.g., "ItemState")</param>
        /// <param name="targetClassName">Name of the target partial ScriptableObject class (e.g., "ItemData")</param>
        /// <param name="memberName">The exact property/field name on target class holding the dictionary (e.g., "Items")</param>
        /// <param name="dict">The dictionary containing string keys</param>
        public static void GenerateFromDictionary<TValue>(string enumName, string targetClassName, string memberName, Dictionary<string, TValue> dict)
        {
            if (dict == null || dict.Count == 0) return;

            string valueTypeName = typeof(TValue).FullName ?? typeof(TValue).Name;

            StringBuilder sb = new();
            sb.AppendLine("// ========================================================");
            sb.AppendLine("// AUTO-GENERATED BY TRASHCOUNT EDITOR. DO NOT EDIT!");
            sb.AppendLine("// ========================================================");
            sb.AppendLine("namespace TrashCount.Data");
            sb.AppendLine("{");

            // 1. GENERATE ENUM
            sb.AppendLine($"    public enum {enumName}");
            sb.AppendLine("    {");
            sb.AppendLine("        None = 0,");

            HashSet<string> cleanKeys = new();
            Dictionary<string, string> keyMap = new();

            foreach (var key in dict.Keys)
            {
                if (string.IsNullOrWhiteSpace(key)) continue;

                string cleanKey = Regex.Replace(key.Trim(), @"[^\w]", "_");
                if (char.IsDigit(cleanKey[0]))
                {
                    cleanKey = "_" + cleanKey;
                }

                if (cleanKeys.Add(cleanKey))
                {
                    keyMap[key] = cleanKey;
                    sb.AppendLine($"        {cleanKey},");
                }
            }

            sb.AppendLine("    }");
            sb.AppendLine("");

            // 2. GENERATE PARTIAL CLASS INDEXER
            sb.AppendLine($"    public partial class {targetClassName}");
            sb.AppendLine("    {");
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// Auto-generated zero-allocation indexer for {enumName}!");
            sb.AppendLine($"        /// </summary>");
            sb.AppendLine($"        public {valueTypeName} this[{enumName} state] => state.GetValue(this);");
            sb.AppendLine("    }");
            sb.AppendLine("");

            // 3. GENERATE EXTENSION LOOKUP METHOD
            sb.AppendLine($"    public static class {enumName}Extensions");
            sb.AppendLine("    {");
            sb.AppendLine($"        public static {valueTypeName} GetValue(this {enumName} state, {targetClassName} data)");
            sb.AppendLine("        {");
            sb.AppendLine($"            if (data == null || data.{memberName} == null) return default;");
            sb.AppendLine("");
            sb.AppendLine("            switch (state)");
            sb.AppendLine("            {");

            foreach (var kvp in keyMap)
            {
                string origKey = kvp.Key;
                string cleanKey = kvp.Value;

                sb.AppendLine($"                case {enumName}.{cleanKey}:");
                sb.AppendLine($"                    return data.{memberName}.TryGetValue(\"{origKey}\", out var v_{cleanKey}) ? v_{cleanKey} : default;");
            }

            sb.AppendLine("                default:");
            sb.AppendLine("                    return default;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            // Write File
            string dirPath = Path.Combine(Application.dataPath, "Scripts", "Generated");
            if (!Directory.Exists(dirPath)) Directory.CreateDirectory(dirPath);

            string filePath = Path.Combine(dirPath, $"{enumName}.cs");
            string newContent = sb.ToString();

            if (File.Exists(filePath) && File.ReadAllText(filePath) == newContent) return;

            File.WriteAllText(filePath, newContent);
            AssetDatabase.Refresh();
        }
    }
}
#endif